### ISSUE TITLE
Find better name for the Panel classes

### ISSUE THREAD

**Issue by philippjfr** [pyviz/panel#1]
After discussing the organization of the ``panel`` library we decided that the ``PanelBase`` class and its subclass are misnamed. This is because we all agreed that the concept of a panel more accurately describes the combination of several components, e.g. a set of widgets with some associated plot. 

The class name for the classes that currently inherit from PanelBase should convey the idea that it is a viewable and reactive object that wraps some other object and displays it as part of some larger panel.

Names that we have considered (and so far rejected):

* ``SubPanel``

CC: @jbednar @ceball @jlstevens

**Comment by jbednar** [comment]
> The class name for the classes that currently inherit from PanelBase should convey the idea that it is a viewable and reactive object that wraps some other object and displays it as part of some larger panel

I agree with all this, except that "displays it as part of some larger panel" is not a defining feature; it's something that *can* be done, but is in no way required.  Just wrapping up an mpl figure as something that displays itself is already a meaningful action, whether or not the result ends up in a panel. That's why I don't like `SubPanel`.

How about `Pane`?

**Comment by jlstevens** [comment]
`Pane` seems to be the best suggestion so far though `View` and `Viewport` were also suggested.
