### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by tadasnik** [pyviz/panel#107]
"pip install panel" completes with "Successfully installed panel-0.0.1 param-1.8.1", but the package can not be import afterwards. Notably, '.../site-packages/panel-0.0.1.dist-info' directory does get created, but the actual package directory '.../site-packages/panel' does not. This is from python3.6 virtual environment.

**Comment by ceball** [comment]
The panel package on PyPI is just a placeholder to reserve the name. Automatic PyPI uploading of releases has been added to panel recently, but no release has been made since then. If you want to try out panel via pip before the next release, you could run something like `pip install --pre --extra-index-url https://test.pypi.org/simple/ "panel>0.1"`.

Alternatively, you can get panel releases and dev versions via conda (e.g. `conda install -c pyviz panel`).

Sorry the documentation at panel.pyviz.org is running a little ahead of reality...

**Comment by ceball** [comment]
Thanks for trying that! Please let us know if you find any problems with the pip package (it won't have been tried much yet, I guess).

Meanwhile, I'll re-open this issue in case it helps anyone else avoid wasting time (until we actually put panel on pypi).

**Comment by jbednar** [comment]
@ceball, there was a full release on Friday, so are you saying you added  pip support to panel since last Friday?  If so let's just tag a new release of Panel so that there are pip versions.  If not seems like it might not be set up properly yet?

**Comment by ceball** [comment]
I wrote my comment above before I saw https://github.com/pyviz/panel/pull/103#issuecomment-431380609. Maybe the plan isn't to wait for that before tagging a release, then? 

(I seem to recall that users will at least get a message from bokeh at the right time telling them to install nodejs, if they don't already have it.)

**Comment by jbednar** [comment]
I think it's too risky to wait for Bokeh 1.0, so @philippjfr agreed that he should tag a Panel release whenever he is done for today.

**Comment by robmarkcole** [comment]
OK I was also getting the error until `pip install --pre --extra-index-url https://test.pypi.org/simple/ "panel>0.1"`

**Comment by philippjfr** [comment]
There should be a release on PyPI now.
