### ISSUE TITLE
Pane vs Row/Column building

### ISSUE THREAD

**Issue by kcpevey** [pyviz/panel#114]
I'm struggling to understand why I would use `Pane` instead of just using `Row` and `Column` to build up a pane. The docs pages on the two are completely exclusive of any mention of one other.   
  
1. Can I mix and match?     
2. What benefit is one over the other?

**Comment by philippjfr** [comment]
Anything that you put into a ``Row`` and ``Columns`` will get turned into a ``Pane`` if it isn't already  a ``Widget``,``Layout`` or ``Pane`` instance. The reason why you might want to construct a Pane manually is that you want to pass some options to that Pane since the Row/Column will just construct a Pane with the default settings.

**Comment by jbednar** [comment]
True; only useful if not using Row and wanting it to be displayable as a Pane nonetheless.

**Comment by kcpevey** [comment]
Ok. I'm going to read through that 3 more times, but I think I'm coming to an understanding.

**Comment by kcpevey** [comment]
Also - I feel like there is analogy to a paned glass door in here somewhere.

**Comment by jbednar** [comment]
There is definitely an analogy to window panes, yes.  But don't get too comfortable; we just [agreed this afternoon to overhaul our terminology](https://github.com/pyviz/panel/issues/124) to make it more consistent and I think more clear, which has the downside of confusing you if you figure out the above!

**Comment by kcpevey** [comment]
@jbednar In that case, I'll hold off spending too much time on terminology at this point!
