### ISSUE TITLE
Pipeline error handling

### ISSUE THREAD

**Issue by kcpevey** [pyviz/panel#163]
All my error handling when using Pipeline is coming back as a string within my pipeline with ONLY the final error string. Is there any way for me to bypass that so I can see the whole traceback? It makes debugging quite difficult.

**Comment by philippjfr** [comment]
>Is there any way for me to bypass that so I can see the whole traceback? It makes debugging quite difficult.

I should probably add a debug mode or similar which reraises the error.

**Comment by kcpevey** [comment]
debug mode was added. leaving this open as a reminder to document.

**Comment by joelostblom** [comment]
Is there a debugging mode available for panels as well? Currently, when a widget send a value that results in an error the function fail silently instead of raising an error for me (using the JupyterLab notebook). I would like errors to be raised to facilitate troubleshoooting. I put an example and some more detail in [this SO question](https://stackoverflow.com/questions/57339953/raise-errors-and-display-traceback-messages-from-panel-dashboards).

**Comment by philippjfr** [comment]
@joelostblom Can you see the error on your browser's JS console?

**Comment by joelostblom** [comment]
@philippjfr Yes I can, thank you! That is definitely helpful for me when developing.

I think it would still be useful with some sort of indication in the notebook or the panel itself that the current widget value caused an error rather than it worked and the output just remained the same. Especially when distributing the dashboard app I am building to my colleagues, they would benefit from having this information available as they play around with their data in the panel.
