### ISSUE TITLE
Should be able to set width on markdown pane

### ISSUE THREAD

**Issue by jsignell** [pyviz/panel#270]
Setting width works well on `pn.pane.Str` but not so much on `pn.pane.Markdown`

<img width="896" alt="screen shot 2019-03-04 at 3 52 52 pm" src="https://user-images.githubusercontent.com/4806877/53762290-b8069880-3e95-11e9-9bbc-75f7621c3229.png">

**Comment by philippjfr** [comment]
It seems like this happens because Markdown wraps the string in a ``<p>`` tag forcing it not to wrap, setting max_width "works" but causes overlap:

![screen shot 2019-03-06 at 2 31 50 am](https://user-images.githubusercontent.com/1550771/53851894-0613bd00-3fb8-11e9-86f8-9286535db8a7.png)

Maybe we should handle this simple case differently? I do think the default representation of a string should respect the set width and therefore wrap, but the only other option we have making ``HTML`` or ``Str`` take priority over ``Markdown``, which would also be a loss in usability imo.

**Comment by jsignell** [comment]
I think having Str as the default would be entirely reasonable. It might actually be clearer since markdown can have some confusing behaviors.

**Comment by jbednar** [comment]
But Str is displayed as fixed-width text; surely very few people want a lot of fixed-width fonts on their dashboards.

**Comment by jbednar** [comment]
Why does a `<p>` not wrap? That seems odd; on a normal HTML page it would, right? Is there CSS we need to override to make it wrap?

**Comment by philippjfr** [comment]
I think this issue is partially a real issue that was resolved and partially a misunderstanding. The first was that wrapping was disabled as a workaround which was removed. The misunderstanding was caused by my test case which has no spaces between characters and therefore has no line breaks, as long as there are line breaks things work fine now.
