### ISSUE TITLE
Altair demo is not working 

### ISSUE THREAD

**Issue by domoritz** [pyviz/panel#468]
I'm seeing an empty plot at https://pyviz-dev.github.io/panel/gallery/apis/stocks_altair.html

<img width="889" alt="Screen Shot 2019-06-03 at 21 05 05" src="https://user-images.githubusercontent.com/589034/58850428-59db8400-8643-11e9-9eb9-90f81662f7e6.png">

**Comment by domoritz** [comment]
Similarly, the altair demo at http://panel.pyviz.org/reference/panes/Vega.html#gallery-vega is also blank.

**Comment by philippjfr** [comment]
Thanks, it seems I forgot to push the fix here, I think there's an issue with cross-origin requests here which is preventing it from fetching the data.

**Comment by sterlinm** [comment]
It seems like after you switch the dropdown selection a few times it starts filling in the data. I was about to open what I assume is a related issue. I was trying to build a dashboard with two dropdowns where the values available in the second dropdown depend on the value of the first dropdown. Here's a dummy example:

```
import altair as alt
import numpy as np
import pandas as pd
import panel as pn
import param

pn.extension('vega')

# Make dummy data
df_data = {
    'var1': sorted(['A','B']*6),
    'var2': ['X', 'X', 'X', 'Y', 'Y', 'Y', 'X', 'X', 'X', 'Z', 'Z', 'Z'],
    'var3': 4*[1, 2, 3],
    'value': np.random.rand(12)
}
df = pd.DataFrame(data=df_data)

class DataViewer(param.Parameterized):
    
    _var2_values = {'A':['X', 'Y'],
                    'B':['X', 'Z']}
    _default_var1 = 'A'
    
    var1 = param.ObjectSelector(default=_default_var1, objects=['A','B'])
    var2 = param.ObjectSelector(default='X', objects=_var2_values[_default_var1])
    
    @param.depends('var1', watch=True)
    def _update_var2(self):
        var2_values = self._var2_values[self.var1]
        self.param['var2'].objects = var2_values
        self.var2 = var2_values[0]
    
    def view_df(self):
        """ Returns the unfiltered DataFrame `df`
        """
        return df
    
    @param.depends('var1', 'var2', watch=True)
    def view_filtered_df(self):
        filtered_df = df.query(f'var1=="{self.var1}" and var2=="{self.var2}"').copy()
        return filtered_df
    
    @param.depends('var1', 'var2', watch=True)
    def plot_filtered_df(self):
        filtered_df = df.query(f'var1=="{self.var1}" and var2=="{self.var2}"').copy()
        chart = alt.Chart(filtered_df, width=250).mark_bar().encode(
            x='var3',
            y='value'
        )
        return chart


viewer = DataViewer(name='Data Viewer')
dashboard = pn.Row(pn.Column(viewer.param, viewer.plot_filtered_df),
       pn.Column(viewer.view_filtered_df, viewer.view_df))

dashboard
```

Here's what it looks like when it's first loaded:

![panel_bug](https://user-images.githubusercontent.com/1461273/58975939-3e33c300-8794-11e9-963f-8d7ea6be4fe1.JPG)

Here's a gif of it eventually filling in data:

![ezgif com-optimize (1)](https://user-images.githubusercontent.com/1461273/58977202-332e6200-8797-11e9-955a-fb7db0ec9a21.gif)

Is this due to the same problem or is there an issue with how I'm understanding the use of param? Thanks!
