### ISSUE TITLE
panel.interact in jupyterlab outputs a pandas Series as latex not html

### ISSUE THREAD

**Issue by SteveAlexander** [pyviz/panel#597]
I'm using jupyterlab 1.0.5 via conda, with `jupyter labextension install @pyviz/jupyterlab_pyviz` applied.

Pandas 0.24.2
Panel 0.6.2
Python 3.7.3
MacOS 10.14.5
Chrome 76.0.3809.100

![image](https://user-images.githubusercontent.com/4321921/62980714-33924b80-be1f-11e9-90e8-ba3c34e23786.png)

```
import pandas as pd
import panel as pn

df = pd.DataFrame([[1, 2, 3], [4, 5, 6]])

pn.extension()

def select_row(row=0):
    return df.loc[row]
app = pn.interact(select_row, row=(0, len(df)-1))
print(app)
app
```

I'm expecting this to produce a slider and HTML rendered table. Instead, for me, it tries to render a katex-rendered table, which causes Bokeh to give an error in the JS console: `Uncaught Error: Model 'KaTeX' does not exist. This could be due to a widget or a custom model not being registered before first usage`

**Comment by philippjfr** [comment]
Oh this actually happens because ``df.loc[row]`` returns a Series which isn't specifically handled.

**Comment by SteveAlexander** [comment]
Confirmed — if I do `return pd.DataFrame([df.loc[row]])` instead, I get a nice table!

![image](https://user-images.githubusercontent.com/4321921/63017588-a981cb80-be8e-11e9-84f3-8c8648094e62.png)

**Comment by SteveAlexander** [comment]
Also, if I change the return to `return df.loc[[row]]` (rather than `return df.loc[row]`), then it works as expected:

![image](https://user-images.githubusercontent.com/4321921/63018035-c539a180-be8f-11e9-849f-edf9a3a0297f.png)

I guess I need to learn to drive Pandas a bit better!

And, I wonder if there's a way Panel could have given me a clearer hint that what I was returning was of a type that couldn't be handled by Panel's HTML renderer? As a Panel and PyViz newbie, my response to seeing 'LaTeX' and 'Katex' in the various output was to try and get my system set up to output those formats, rather than understanding that I could have been returning a more appropriate type. I expect that with a little more experience, I wouldn't have been caught by this in the same way.

**Comment by jbednar** [comment]
I feel your pain!  I suspect it will be very tricky to raise such a warning in the general case, because Panel is specifically designed to display anything that you give it, so in this case it tries to display the Series using the Series's rich display methods.  We should of course fix our priority declarations to avoid trying a LaTeX-based display on a system not set up for it, and we can add specific support for a Series, but in general we can't know what people might be trying to display and whether that's valid or appropriate, so it would be difficult to warn reliably. :-(
